spring.application.name=springboot-blog-resp-api
# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/myblog
spring.datasource.username=root
spring.datasource.password=Singh#123
# spring boot 3 -> we can remove below line , spring boot 3 uses hibernate 6 which automatically configure the dialect for us
# based on the driver dependency that we add to the classpath.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
# include this line to show message in response
server.error.include-message=always

